### ISSUE TITLE
Inverse problem: from data.frame to fwf/md output

### ISSUE THREAD

**Issue by dmi3kno** [MilesMcBain/datapasta#136]
Perhaps this function does not belong to the package, but have you ever considered the inverse problem: Going from a data.frame to 

- a fixed-width file output (of other format) in clipboard, which would be pasteable into Excel or Word.
- a simple "pipe-decorated" markdown table to be pasted to md/Rmd/Qmd

This would be helpful in writing non-reproducible documents, which I do have to do every now and then. I will understand if the answer is an emphatic "NO!"

**Comment by MilesMcBain** [comment]
Thanks for the thoughts!

> a fixed-width file output (of other format) in clipboard, which would be pasteable into Excel or Word.

For this I use `df |> clipr::write_clip()`.

> a simple “pipe-decorated” markdown table to be pasted to md/Rmd/Qmd

I do this from time to time, since I use MailMate which supports markdown email authoring. So when I have to paste a table from my R session It’s like `dt |> knitr::kable()` followed by a manual copy paste from the R terminal. But it turns out `{clipr}` seems to be the goods here as well:

``` r
mtcars |> knitr::kable() |> clipr::write_clip()
```

These little cantrips are so simple, it doesn’t make much sense to me to implement them in this package. So checkout `{clipr}`!
