### ISSUE TITLE
Update no clipboard error message with instructions for clipboard packages install. Like Clipr.

### ISSUE THREAD

**Issue by MilesMcBain** [MilesMcBain/datapasta#42]

**Comment by jonocarroll** [comment]
More of an issue for `clipr` itself perhaps (cc: @mdlincoln) but since we recommend it, can we confirm that `xsel` is compatible? I just tried it out on a new install (Ubuntu 16.04.2) and `clipr::clipr_available()` just returns `FALSE` with only `xsel` installed correctly. Installing `xclip` fixed everything.

Relevant to this issue since the instructions may need to point to one/both of these.

**Comment by MilesMcBain** [comment]
Thanks for pointing this out. I was able to reproduce on a new Ubuntu 16.10 installation as well. I'll do some investigation from the `clipr` side to see if that's going to be an easy pull. Otherwise we can just update the doco to remove `xsel`.

**Comment by mdlincoln** [comment]
👀  it's true, clipr actually doesn't explicitly have a test set up to evaluate against _just_ xsel right now! I'll look in to establishing a reliable test for that on Travis... and then i'm curious to see what's going wrong with clipr -> xsel itself

**Comment by MilesMcBain** [comment]
I've made a [pull request over on clipr](https://github.com/mdlincoln/clipr/pull/26) to fix `xsel`. Although that issue indirectly caused me to raise this (I was getting unexpected errors on the `datapasta` end), I still think the `datapasta` error message needs to be transparent in the case of `xsel` or `xclip` not found.

**Comment by mdlincoln** [comment]
[clipr 0.3.3](https://github.com/mdlincoln/clipr/releases/tag/v0.3.3) is now on CRAN

**Comment by MilesMcBain** [comment]
That's awesome! Thanks!
