### ISSUE TITLE
Error: strrep invalid "times" value

### ISSUE THREAD

**Issue by dmi3kno** [MilesMcBain/datapasta#77]
The following data frame can not be pasted as tribble:
```r
df <- data.frame(stringsAsFactors=FALSE,
          X1 = c("b", "c", "C", "g", "g", "G", "L", "L", "L", "L", "I", "I",
                 "I", "I", "l", "l", "l", "l", "O", "S", "V", "Z", "a", "d",
                 "g", "m", "A", "A", "A", "W", "M", "M", "M", "M", "A", "B", "B",
                 "D", "D", "G", "H", "H", "K", "K", "L", "L", "N", "N", "V"),
          X2 = c("6", "(", NA, "q", "9", "6", "I", "l", "1", "|", "l", "1",
                 "|", "L", "I", "L", "1", "|", "0", "5", "U", "2", "ci", "cl",
                 "cj", "rn", "fi", "fl", "fI", "VV", "IVI", "lvl", "Ivl", "lvI",
                 "/\\", "l3", "I3", "I)", "l)", "(¬", "I-I", "l-l", "l<", "l{",
                 "l_", "I_", "l\\l", "I\\I", "\\/")
)

datapasta::tribble_paste(df)
#> Error in strrep(" ", char_length - nchar(char_vec)) : 
#>   invalid 'times' value
```
interestingly enough `vector_paste_vertical` works on both `X1` and `X2`

**Comment by jonocarroll** [comment]
Well, this is an interesting one. The reason this is failing is that there's some padding that needs to happen. In order to do that, we need to know the width of the values and add sufficient `" "` with `strrep`. 

Minimal reproducible example:

```r
df <- data.frame(stringsAsFactors = FALSE,
                 X1 = c("a", "b", "c"),
                 X2 = c("x", "l\\l", "z")
)
tribble_paste(df)
```
Here's the fun bit: the call which is failing is

```r
paste0(strrep(" ",char_length - nchar(char_vec)),char_vec)
```

where `char_length = 5` and `char_vec = "l\\l"`. Easy, right?

```r
nchar("l\\l")
#> 3
```
Confirmed by `strsplit`:

```r
strsplit("l\\l", "")
#> [[1]]
#> [1] "l"  "\\" "l" 
```

What it's actually seeing, however (found via debug) is

```r
c("\"", "l", "\\", "\\", "l", "\"")
```

resulting in `5-6` and an invalid number of times to repeat something.

What I don't see, is where the extra backslashes are being added. The function is definitely receiving `"\"l\\\\l\""` as input, which looks like something is trying to `paste` extra `\` in. Half-way there.
